name: Deploy Medusa to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: SSH into EC2 and deploy Medusa
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: 3.88.91.83
        username: ubuntu
        password: anik
        script: |
          cd ~/my-medusa-store
          git pull origin main
          npm install
          medusa develop &
